apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appNames.firstAppName  }}-cluster-ip-service
spec:
  type: {{ .Values.appServices.firstAppServiceType  }}
  selector:
    app: {{ .Values.appNames.firstAppName  }}
  ports:
    - port: {{ .Values.appServices.firstAppServicePort }}
      targetPort: {{ .Values.appImages.firstAppPort }}
